import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        outline: '#958da1',
        'tertiary-container': '#a15100',
        'surface-container-lowest': '#100d16',
        'primary-fixed-dim': '#d2bbff',
        'on-tertiary-fixed-variant': '#713700',
        'on-primary-container': '#ede0ff',
        tertiary: '#ffb784',
        'on-primary-fixed': '#25005a',
        error: '#ffb4ab',
        'inverse-primary': '#732ee4',
        'secondary-container': '#523787',
        background: '#15121b',
        'surface-container-low': '#1d1a24',
        'on-surface-variant': '#ccc3d8',
        'on-secondary-fixed': '#25005a',
        primary: '#d2bbff',
        'tertiary-fixed': '#ffdcc6',
        'error-container': '#93000a',
        'on-tertiary': '#4f2500',
        'surface-container-high': '#2c2833',
        'outline-variant': '#4a4455',
        'on-secondary': '#3b1e6f',
        'surface-tint': '#d2bbff',
        'surface-container': '#221e28',
        'on-background': '#e8dfee',
        'inverse-on-surface': '#332f39',
        surface: '#15121b',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb784',
        'surface-variant': '#37333e',
        'inverse-surface': '#e8dfee',
        'surface-dim': '#15121b',
        'primary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bbff',
        'on-tertiary-container': '#ffe0cd',
        'secondary-fixed': '#eaddff',
        'on-secondary-container': '#c3a6ff',
        'on-secondary-fixed-variant': '#523787',
        'on-error': '#690005',
        'surface-bright': '#3c3742',
        'primary-container': '#7c3aed',
        'on-primary-fixed-variant': '#5a00c6',
        'on-tertiary-fixed': '#301400',
        'surface-container-highest': '#37333e',
        'on-surface': '#e8dfee',
        'on-primary': '#3f008e',
        secondary: '#d2bbff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'sidebar-width': '240px',
        'table-cell-padding-v': '8px',
        'container-margin': '24px',
        gutter: '16px',
        unit: '4px',
        'table-cell-padding-h': '12px',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'mono-data': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};

export default config;
