import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        outline: '#475569',
        'outline-variant': '#1e2532',
        background: '#090b0e',
        surface: '#0f1217',
        'surface-container-lowest': '#090b0e',
        'surface-container-low': '#12161e',
        'surface-container': '#151922',
        'surface-container-high': '#1a202c',
        'surface-container-highest': '#222938',
        'on-surface': '#f1f5f9',
        'on-surface-variant': '#94a3b8',
        'on-background': '#f1f5f9',
        primary: '#f59e0b',
        'primary-container': '#d97706',
        'on-primary': '#000000',
        'on-primary-container': '#fef3c7',
        secondary: '#94a3b8',
        'secondary-container': '#1e293b',
        'on-secondary': '#0f172a',
        'on-secondary-container': '#e2e8f0',
        tertiary: '#10b981',
        'tertiary-container': '#065f46',
        'on-tertiary': '#000000',
        'on-tertiary-container': '#d1fae5',
        error: '#f87171',
        'error-container': '#7f1d1d',
        'on-error': '#ffffff',
        'on-error-container': '#fecaca',
        'surface-variant': '#1e2532',
        'inverse-surface': '#f1f5f9',
        'inverse-on-surface': '#090b0e',
        'surface-dim': '#090b0e',
        'surface-bright': '#222938',
        'surface-tint': '#f59e0b',
      },
      borderRadius: {
        none: '0',
        sm: '0.25rem',
        DEFAULT: '0.375rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '240px',
        'table-cell-padding-v': '8px',
        'container-margin': '24px',
        gutter: '16px',
        unit: '4px',
        'table-cell-padding-h': '12px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'mono-data': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};

export default config;
